server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config:
      microservice-provider-user:
        connectTimeout: 5000 #相当于Request.Options
        readTimeout: 11000 #相当于Request.Options
