
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
spring:
  application:
    name: eureka
server:
  port: 8761