spring:
  application:
    name: eureka-authenticating
  security:
    user:
      name: user
      password: password
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
server:
  port: 8761