server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/, http://peer2:8762/eureka/
logging:
  level:
    root: INFO
    # 配置日志级别，让hibernate打印出执行的SQL参数
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.springframework.cloud.sleuth: DEBUG
management:
  endpoints:
    web:
      exposure:
        # 开放所有监控端点
        include: '*'
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always